### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by sunny596** [hyukhur/libphonenumber-swift#1]
Hi,
Thanks for your hardwork.

How do I add this to my xcode project manually ? 
Can you tell us how to use this library for iPhone ? Any example snippets ?

Hope to hear from you.
Thanks in advance.

**Comment by hyukhur** [comment]
@sunny596 
I'm so sorry that the library is not ready and is still implementing.
let me known what feature you want to use. then I'll change the priority.

**Comment by sunny596** [comment]
Hi, thanks for your prompt reply.

I need to convert phone numbers from Address Book to E164 format and check the validity. The country code is known to us. 

Eg. Convert (013) 555-5555 with country code +60 into E164.
Result :
E164 format: +60135555555
isPossibleNumber(): true
isValidNumber(): true

If it helps, something on the lines of 
http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html

Thank you for your time.

**Comment by hyukhur** [comment]
It needs the full feature of libphonenumber lib.
This lib's mission is the complete compatibility of javascript lib of google's libphonenumber.
What about the objective-c porting lib? ( https://github.com/iziz/libPhoneNumber-iOS )
It's well made library. Guarantee it.
